### PR TITLE
Fix inaccurate formatting of exponential numbers

### LINKED ISSUE #330: Sending less than $0.004 worth of BTC results in sending a large amount of BTC
If you enter 0.003 in USD in the fiat field when sending BTC, the resulting amount in the BTC field reads 8.41057040

### PR DESCRIPTION
**Pull request by zachgibb**
Fixes #330 

This was caused by the string formatter reading numbers like `2e-5` as just `2` instead of `0.00002`. I have now put in a function which will first format the numbers as decimal values before trimming to a given precision.

### CODE REVIEW

File: src/lib/formatters.js [hunk 1]
```diff
@@ -1,10 +1,67 @@
...
+    const trimmedDecimals = finalDecimals.replace(/0*$/, '');
+
+    // ensure there is only one leading 0 on integers
+    const trimmedIntegers =
+      finalIntegers.replace(/^0*/, '') || '0'; // trim leading 0s // ensure there is at least 1 leading 0 if no integers
+
+    // if there are decimals after trimming
+    // return integers and decimals separated by "."
+    if (trimmedDecimals.length) {
+      return `${trimmedIntegers}.${trimmedDecimals}`;
```
Comment (ericgibb) [inline src/lib/formatters.js]: i18n delimited formats will differ here. I think this should be in the en.lang file to allow for multiple formats in the future

File: src/lib/formatters.js [hunk 2]
```diff
@@ -1,10 +1,67 @@
...
+
 export const limitNumber = PRECISION => value =>
   Number(value.toFixed(PRECISION));
 
 export const limitDecimalString = PRECISION => value => {
-  const halves = value.split('.');
+  const halves = exponentialToDecimal(value).split('.');
   const [integers, decimals] = halves;
   if (halves.length === 2) {
     return `${integers}.${decimals.substring(0, PRECISION)}`;
```
Comment (ericgibb) [inline src/lib/formatters.js]: i18n here, too.

File: src/lib/formatters.js (hunk 1 above)
Comment (ericgibb) [reply src/lib/formatters.js]: (after discussion, we decided to spin off into new app-wide fix)

File: src/lib/formatters.js (hunk 2 above)
Comment (ericgibb) [reply src/lib/formatters.js]: (after discussion, we decided to spin off into new app-wide fix)
